export const FETCH_BLOG_DATA = 'FETCH_BLOG_DATA';
export const REMOVE_ARTICLES = 'REMOVE_ARTICLES';
export const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID';
export const REMOVE_ARTICLE_STATE = 'REMOVE_ARTICLE_STATE';
export const GET_ARTICLE_BY_CATEGORY = 'GET_ARTICLE_BY_CATEGORY';


export const FETCH_CATEGORIES_DATA = 'FETCH_CATEGORIES_DATA';
export const REMOVE_CATEGORIES = 'REMOVE_CATEGORIES';